INSERT INTO cat (id,pettype,trackertype,ownerid,inzone,losttracker) VALUES ('1', 'CAT', 'L', 123, true, false);
INSERT INTO cat (id,pettype,trackertype,ownerid,inzone,losttracker) VALUES ('2', 'CAT', 'S', 123, true, false);
INSERT INTO cat (id,pettype,trackertype,ownerid,inzone,losttracker) VALUES ('3', 'CAT', 'M', 123, false, false);
INSERT INTO cat (id,pettype,trackertype,ownerid,inzone,losttracker) VALUES ('4', 'CAT', 'L', 123, true, false);
INSERT INTO cat (id,pettype,trackertype,ownerid,inzone,losttracker) VALUES ('5', 'CAT', 'S', 123, true, false);
INSERT INTO cat (id,pettype,trackertype,ownerid,inzone,losttracker) VALUES ('6', 'CAT', 'M', 123, false, false);
INSERT INTO dog (id,pettype,trackertype,ownerid,inzone) VALUES ('1', 'DOG', 'L', 123, true);
INSERT INTO dog (id,pettype,trackertype,ownerid,inzone) VALUES ('2', 'DOG', 'L', 123, false);
INSERT INTO dog (id,pettype,trackertype,ownerid,inzone) VALUES ('3', 'DOG', 'M', 123, true);
INSERT INTO dog (id,pettype,trackertype,ownerid,inzone) VALUES ('4', 'DOG', 'M', 123, false);
INSERT INTO dog (id,pettype,trackertype,ownerid,inzone) VALUES ('5', 'DOG', 'M', 123, false);
INSERT INTO dog (id,pettype,trackertype,ownerid,inzone) VALUES ('6', 'DOG', 'M', 123, true);
INSERT INTO dog (id,pettype,trackertype,ownerid,inzone) VALUES ('7', 'DOG', 'S', 123, false);